server:
  port: 4001

management:
  endpoints:
    enabled-by-default: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: localhost:5001/eureka
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: root
