server:
  port: 4001

management:
  endpoints:
    enabled-by-default: true

eureka:
  datasource:
    url: jdbc:mysql://localhost/micro
    username: root
    password: root
  jpa:
    generate-ddl: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5001/eureka
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: root
